const score = {
  scorecard: [
    {
      inningsid: 1,
      batsman: [
        {
          id: 11050,
          balls: 11,
          runs: 18,
          fours: 4,
          sixes: 0,
          strkrate: "163.64",
          name: "D Arcy Short",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "b Hemant Dhami",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1464923,
          balls: 14,
          runs: 18,
          fours: 3,
          sixes: 0,
          strkrate: "128.57",
          name: "Sumit Maharjan",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "lbw b Harmeet Singh",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 12140,
          balls: 36,
          runs: 35,
          fours: 3,
          sixes: 0,
          strkrate: "97.22",
          name: "Rohit Paudel",
          nickname: "",
          iscaptain: true,
          iskeeper: false,
          outdec: "c Bhandari b Hemant Dhami",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 12726,
          balls: 29,
          runs: 31,
          fours: 2,
          sixes: 1,
          strkrate: "106.9",
          name: "Dilip Nath",
          nickname: "",
          iscaptain: false,
          iskeeper: true,
          outdec: "c Bhandari b Abinash Bohara",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 8030,
          balls: 9,
          runs: 11,
          fours: 2,
          sixes: 0,
          strkrate: "122.22",
          name: "Gulbadin",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Bhandari b Abinash Bohara",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 14431,
          balls: 3,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Trumpelmann",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "run out (Dipendra Singh)",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 14220,
          balls: 7,
          runs: 7,
          fours: 0,
          sixes: 0,
          strkrate: "100",
          name: "Sundeep Jora",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Kuggeleijn b Abinash Bohara",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 22716,
          balls: 2,
          runs: 4,
          fours: 1,
          sixes: 0,
          strkrate: "200",
          name: "Sher Malla",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "b Kuggeleijn",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1426791,
          balls: 4,
          runs: 6,
          fours: 1,
          sixes: 0,
          strkrate: "150",
          name: "Thomas Draca",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Dipendra Singh b Harmeet Singh",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "IN",
        },
        {
          id: 22746,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Tilak Bhandari",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "not out",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1464928,
          balls: 3,
          runs: 6,
          fours: 1,
          sixes: 0,
          strkrate: "200",
          name: "Abhishesh Gautam",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Dipendra Singh b Harmeet Singh",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
      ],
      bowler: [
        {
          id: 9511,
          overs: "4",
          maidens: 0,
          wickets: 1,
          runs: 28,
          economy: "7",
          name: "Kuggeleijn",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 24,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 11155,
          overs: "4",
          maidens: 0,
          wickets: 0,
          runs: 30,
          economy: "7.5",
          name: "Dipendra Singh",
          nickname: "",
          iscaptain: true,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 24,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 52579,
          overs: "3",
          maidens: 0,
          wickets: 2,
          runs: 28,
          economy: "9.3",
          name: "Hemant Dhami",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 18,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 8426,
          overs: "3.4",
          maidens: 0,
          wickets: 3,
          runs: 22,
          economy: "6",
          name: "Harmeet Singh",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 22,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1448021,
          overs: "1",
          maidens: 0,
          wickets: 0,
          runs: 6,
          economy: "6",
          name: "Naren Saud",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 6,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 14556,
          overs: "4",
          maidens: 0,
          wickets: 3,
          runs: 26,
          economy: "6.5",
          name: "Abinash Bohara",
          nickname: "",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 24,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
      ],
      fow: {
        fow: [
          {
            batsmanid: 11050,
            batsmanname: "D Arcy Short",
            overnbr: 2.5,
            runs: 26,
            ballnbr: 17,
          },
          {
            batsmanid: 1464923,
            batsmanname: "Sumit Maharjan",
            overnbr: 6.3,
            runs: 52,
            ballnbr: 39,
          },
          {
            batsmanid: 12140,
            batsmanname: "Rohit Paudel",
            overnbr: 14.1,
            runs: 104,
            ballnbr: 85,
          },
          {
            batsmanid: 8030,
            batsmanname: "Gulbadin",
            overnbr: 16.2,
            runs: 119,
            ballnbr: 98,
          },
          {
            batsmanid: 14431,
            batsmanname: "Trumpelmann",
            overnbr: 16.5,
            runs: 119,
            ballnbr: 101,
          },
          {
            batsmanid: 12726,
            batsmanname: "Dilip Nath",
            overnbr: 16.6,
            runs: 120,
            ballnbr: 102,
          },
          {
            batsmanid: 22716,
            batsmanname: "Sher Malla",
            overnbr: 17.6,
            runs: 129,
            ballnbr: 108,
          },
          {
            batsmanid: 14220,
            batsmanname: "Sundeep Jora",
            overnbr: 18.6,
            runs: 137,
            ballnbr: 114,
          },
          {
            batsmanid: 1426791,
            batsmanname: "Thomas Draca",
            overnbr: 19.1,
            runs: 137,
            ballnbr: 115,
          },
          {
            batsmanid: 1464928,
            batsmanname: "Abhishesh Gautam",
            overnbr: 19.4,
            runs: 143,
            ballnbr: 118,
          },
        ],
      },
      extras: {
        legbyes: 1,
        byes: 2,
        wides: 4,
        noballs: 0,
        penalty: 0,
        total: 7,
      },
      pp: {
        powerplay: [
          {
            id: 8,
            ovrfrom: 0.1,
            ovrto: 6,
            pptype: "mandatory",
            run: 50,
            wickets: 0,
          },
        ],
      },
      score: 143,
      wickets: 10,
      overs: 19.4,
      runrate: 7.27,
      batteamname: "Lumbini Lions",
      batteamsname: "LUL",
      isdeclared: false,
      isfollowon: false,
      ballnbr: 118,
      rpb: 1.21,
      partnership: {
        partnership: [
          {
            id: 0,
            bat1id: 11050,
            bat1name: "D Arcy Short",
            bat1runs: 18,
            bat1fours: 4,
            bat1sixes: 0,
            bat2id: 1464923,
            bat2name: "Sumit Maharjan",
            bat2runs: 8,
            bat2fours: 2,
            bat2sixes: 0,
            totalruns: 26,
            totalballs: 17,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 12140,
            bat1name: "Rohit Paudel",
            bat1runs: 14,
            bat1fours: 2,
            bat1sixes: 0,
            bat2id: 1464923,
            bat2name: "Sumit Maharjan",
            bat2runs: 10,
            bat2fours: 1,
            bat2sixes: 0,
            totalruns: 26,
            totalballs: 22,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 12140,
            bat1name: "Rohit Paudel",
            bat1runs: 21,
            bat1fours: 1,
            bat1sixes: 0,
            bat2id: 12726,
            bat2name: "Dilip Nath",
            bat2runs: 28,
            bat2fours: 2,
            bat2sixes: 1,
            totalruns: 52,
            totalballs: 46,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 8030,
            bat1name: "Gulbadin",
            bat1runs: 11,
            bat1fours: 2,
            bat1sixes: 0,
            bat2id: 12726,
            bat2name: "Dilip Nath",
            bat2runs: 3,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 15,
            totalballs: 13,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 14431,
            bat1name: "Trumpelmann",
            bat1runs: 0,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 12726,
            bat2name: "Dilip Nath",
            bat2runs: 0,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 0,
            totalballs: 3,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 14220,
            bat1name: "Sundeep Jora",
            bat1runs: 0,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 12726,
            bat2name: "Dilip Nath",
            bat2runs: 0,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 1,
            totalballs: 1,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 14220,
            bat1name: "Sundeep Jora",
            bat1runs: 5,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 22716,
            bat2name: "Sher Malla",
            bat2runs: 4,
            bat2fours: 1,
            bat2sixes: 0,
            totalruns: 9,
            totalballs: 6,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 14220,
            bat1name: "Sundeep Jora",
            bat1runs: 2,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 1426791,
            bat2name: "Thomas Draca",
            bat2runs: 6,
            bat2fours: 1,
            bat2sixes: 0,
            totalruns: 8,
            totalballs: 6,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 22746,
            bat1name: "Tilak Bhandari",
            bat1runs: 0,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 1426791,
            bat2name: "Thomas Draca",
            bat2runs: 0,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 0,
            totalballs: 1,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 22746,
            bat1name: "Tilak Bhandari",
            bat1runs: 0,
            bat1fours: 0,
            bat1sixes: 0,
            bat2id: 1464928,
            bat2name: "Abhishesh Gautam",
            bat2runs: 6,
            bat2fours: 1,
            bat2sixes: 0,
            totalruns: 6,
            totalballs: 3,
            bat1balls: 0,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
        ],
      },
    },
    {
      inningsid: 2,
      batsman: [
        {
          id: 36307,
          balls: 7,
          runs: 9,
          fours: 2,
          sixes: 0,
          strkrate: "128.57",
          name: "Josh Brown",
          nickname: "Josh Brown",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Sher Malla b Abhishesh Gautam",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 9961,
          balls: 49,
          runs: 69,
          fours: 5,
          sixes: 4,
          strkrate: "140.82",
          name: "Binod Bhandari",
          nickname: "Bhandari",
          iscaptain: false,
          iskeeper: true,
          outdec: "not out",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 7752,
          balls: 14,
          runs: 16,
          fours: 1,
          sixes: 2,
          strkrate: "114.29",
          name: "Chris Lynn",
          nickname: "Chris Lynn",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Gulbadin b Trumpelmann",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 10126,
          balls: 37,
          runs: 39,
          fours: 4,
          sixes: 1,
          strkrate: "105.41",
          name: "Aarif Sheikh",
          nickname: "Aarif Sheikh",
          iscaptain: false,
          iskeeper: false,
          outdec: "c Rohit Paudel b Tilak Bhandari",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 8426,
          balls: 3,
          runs: 7,
          fours: 0,
          sixes: 1,
          strkrate: "233.33",
          name: "Harmeet Singh",
          nickname: "Harmeet Singh",
          iscaptain: false,
          iskeeper: false,
          outdec: "not out",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 11165,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Ishan Pandey",
          nickname: "Ishan Pandey",
          iscaptain: false,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 11155,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Dipendra Singh Airee",
          nickname: "Dipendra Singh",
          iscaptain: true,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 9511,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Scott Kuggeleijn",
          nickname: "Kuggeleijn",
          iscaptain: false,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1448021,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Naren Saud",
          nickname: "Naren Saud",
          iscaptain: false,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 52579,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Hemant Dhami",
          nickname: "Hemant Dhami",
          iscaptain: false,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 14556,
          balls: 0,
          runs: 0,
          fours: 0,
          sixes: 0,
          strkrate: "0",
          name: "Abinash Bohara",
          nickname: "Abinash Bohara",
          iscaptain: false,
          iskeeper: false,
          outdec: "",
          videotype: "",
          videourl: "",
          videoid: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          iscbplusfree: false,
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
      ],
      bowler: [
        {
          id: 14431,
          overs: "3",
          maidens: 0,
          wickets: 1,
          runs: 27,
          economy: "9",
          name: "Ruben Trumpelmann",
          nickname: "Trumpelmann",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 18,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1464928,
          overs: "4",
          maidens: 0,
          wickets: 1,
          runs: 20,
          economy: "5",
          name: "Abhishesh Gautam",
          nickname: "Abhishesh Gautam",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 24,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 22716,
          overs: "1",
          maidens: 0,
          wickets: 0,
          runs: 12,
          economy: "12",
          name: "Sher Malla",
          nickname: "Sher Malla",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 6,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 1426791,
          overs: "3.2",
          maidens: 0,
          wickets: 0,
          runs: 26,
          economy: "7.8",
          name: "Thomas Draca",
          nickname: "Thomas Draca",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 20,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "IN",
        },
        {
          id: 11050,
          overs: "3",
          maidens: 0,
          wickets: 0,
          runs: 22,
          economy: "7.3",
          name: "D Arcy Short",
          nickname: "D Arcy Short",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 18,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 8030,
          overs: "3",
          maidens: 0,
          wickets: 0,
          runs: 27,
          economy: "9",
          name: "Gulbadin Naib",
          nickname: "Gulbadin",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 18,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
        {
          id: 22746,
          overs: "1",
          maidens: 0,
          wickets: 1,
          runs: 8,
          economy: "8",
          name: "Tilak Bhandari",
          nickname: "Tilak Bhandari",
          iscaptain: false,
          iskeeper: false,
          videotype: "",
          videourl: "",
          videoid: 0,
          dots: 0,
          balls: 6,
          rpb: 0,
          planid: 0,
          imageid: 0,
          premiumvideourl: "",
          ispremiumfree: false,
          inmatchchange: "",
          isoverseas: false,
          playingxichange: "",
        },
      ],
      fow: {
        fow: [
          {
            batsmanid: 36307,
            batsmanname: "Josh Brown",
            overnbr: 1.2,
            runs: 10,
            ballnbr: 8,
          },
          {
            batsmanid: 7752,
            batsmanname: "Chris Lynn",
            overnbr: 4.5,
            runs: 39,
            ballnbr: 29,
          },
          {
            batsmanid: 10126,
            batsmanname: "Aarif Sheikh",
            overnbr: 17.5,
            runs: 138,
            ballnbr: 107,
          },
        ],
      },
      extras: {
        legbyes: 3,
        byes: 0,
        wides: 2,
        noballs: 0,
        penalty: 0,
        total: 5,
      },
      pp: {
        powerplay: [
          {
            id: 9,
            ovrfrom: 0.1,
            ovrto: 6,
            pptype: "mandatory",
            run: 44,
            wickets: 0,
          },
        ],
      },
      score: 145,
      wickets: 3,
      overs: 18.2,
      runrate: 7.91,
      batteamname: "Sudur Paschim Royals",
      batteamsname: "SPR",
      isdeclared: false,
      isfollowon: false,
      ballnbr: 110,
      rpb: 1.32,
      partnership: {
        partnership: [
          {
            id: 0,
            bat1id: 36307,
            bat1name: "Josh Brown",
            bat1runs: 9,
            bat1fours: 2,
            bat1sixes: 0,
            bat2id: 9961,
            bat2name: "Bhandari",
            bat2runs: 0,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 10,
            totalballs: 8,
            bat1balls: 7,
            bat2balls: 1,
            teamname: "",
            teamid: 0,
            bat1ones: 1,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 2,
            bat1sixers: 0,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 7752,
            bat1name: "Chris Lynn",
            bat1runs: 16,
            bat1fours: 1,
            bat1sixes: 2,
            bat2id: 9961,
            bat2name: "Bhandari",
            bat2runs: 13,
            bat2fours: 3,
            bat2sixes: 0,
            totalruns: 29,
            totalballs: 21,
            bat1balls: 14,
            bat2balls: 7,
            teamname: "",
            teamid: 0,
            bat1ones: 0,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 1,
            bat1sixers: 2,
            bat2ones: 1,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 3,
            bat2sixers: 0,
          },
          {
            id: 0,
            bat1id: 10126,
            bat1name: "Aarif Sheikh",
            bat1runs: 40,
            bat1fours: 4,
            bat1sixes: 1,
            bat2id: 9961,
            bat2name: "Bhandari",
            bat2runs: 56,
            bat2fours: 2,
            bat2sixes: 4,
            totalruns: 100,
            totalballs: 79,
            bat1balls: 38,
            bat2balls: 41,
            teamname: "",
            teamid: 0,
            bat1ones: 16,
            bat1twos: 1,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 4,
            bat1sixers: 1,
            bat2ones: 18,
            bat2twos: 3,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 2,
            bat2sixers: 4,
          },
          {
            id: 0,
            bat1id: 8426,
            bat1name: "Harmeet Singh",
            bat1runs: 7,
            bat1fours: 0,
            bat1sixes: 1,
            bat2id: 9961,
            bat2name: "Bhandari",
            bat2runs: 0,
            bat2fours: 0,
            bat2sixes: 0,
            totalruns: 7,
            totalballs: 3,
            bat1balls: 3,
            bat2balls: 0,
            teamname: "",
            teamid: 0,
            bat1ones: 1,
            bat1twos: 0,
            bat1threes: 0,
            bat1fives: 0,
            bat1boundaries: 0,
            bat1sixers: 1,
            bat2ones: 0,
            bat2twos: 0,
            bat2threes: 0,
            bat2fives: 0,
            bat2boundaries: 0,
            bat2sixers: 0,
          },
        ],
      },
    },
  ],
  ismatchcomplete: true,
  appindex: {
    seotitle:
      "Cricket scorecard - LUL vs SPR 13th Match,Nepal Premier League 2025 | Cricbuzz.com",
    weburl:
      "http://www.cricbuzz.com/live-cricket-scorecard/137973/lul-vs-spr-13th-match-nepal-premier-league-2025",
  },
  status: "Sudur Paschim Royals won by 7 wkts",
  responselastupdated: 1764235215,
};
