export const matchContextdata = {
  match: {
    name: "Lumbini Lions vs Sudur Paschim Royals",
    team1: "Lumbini Lions",
    team2: "Sudur Paschim Royals",
    team1Short: "LUL",
    team2Short: "SPR",
    format: "T20",
    status: "Sudur Paschim Royals won by 7 wkts",
    venue: "",
    isMatchComplete: false,
  },
  innings: {
    inningsid: 2,
    runs: 145,
    wickets: 3,
    overs: 18.2,
    batteamname: "Sudur Paschim Royals",
    batteamsname: "SPR",
    partnership: {
      totalRuns: 50,
      totalBalls: 8,
      bat1: {
        name: "Josh Brown",
        runs: 9,
        balls: 7,
      },
      bat2: {
        name: "Bhandari",
        runs: 0,
        balls: 1,
      },
    },
    batsman: [
      {
        id: 36307,
        balls: 7,
        runs: 9,
        fours: 2,
        sixes: 0,
        strkrate: "128.57",
        name: "Josh Brown",
        nickname: "Josh Brown",
        iscaptain: false,
        iskeeper: false,
        outdec: "c Sher Malla b Abhishesh Gautam",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 9961,
        balls: 49,
        runs: 69,
        fours: 5,
        sixes: 4,
        strkrate: "140.82",
        name: "Binod Bhandari",
        nickname: "Bhandari",
        iscaptain: false,
        iskeeper: true,
        outdec: "batting",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 7752,
        balls: 14,
        runs: 16,
        fours: 1,
        sixes: 2,
        strkrate: "114.29",
        name: "Chris Lynn",
        nickname: "Chris Lynn",
        iscaptain: false,
        iskeeper: false,
        outdec: "c Gulbadin b Trumpelmann",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 10126,
        balls: 37,
        runs: 39,
        fours: 4,
        sixes: 1,
        strkrate: "105.41",
        name: "Aarif Sheikh",
        nickname: "Aarif Sheikh",
        iscaptain: false,
        iskeeper: false,
        outdec: "c Rohit Paudel b Tilak Bhandari",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 8426,
        balls: 3,
        runs: 7,
        fours: 0,
        sixes: 1,
        strkrate: "233.33",
        name: "Harmeet Singh",
        nickname: "Harmeet Singh",
        iscaptain: false,
        iskeeper: false,
        outdec: "batting",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 11165,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Ishan Pandey",
        nickname: "Ishan Pandey",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 11155,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Dipendra Singh Airee",
        nickname: "Dipendra Singh",
        iscaptain: true,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 9511,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Scott Kuggeleijn",
        nickname: "Kuggeleijn",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 1448021,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Naren Saud",
        nickname: "Naren Saud",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 52579,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Hemant Dhami",
        nickname: "Hemant Dhami",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 14556,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Abinash Bohara",
        nickname: "Abinash Bohara",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
    ],
    bowler: [
      {
        id: 14431,
        overs: "3",
        maidens: 0,
        wickets: 5,
        runs: 27,
        economy: "9",
        name: "Ruben Trumpelmann",
        nickname: "Trumpelmann",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 18,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 1464928,
        overs: "4",
        maidens: 0,
        wickets: 1,
        runs: 20,
        economy: "5",
        name: "Abhishesh Gautam",
        nickname: "Abhishesh Gautam",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 24,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 22716,
        overs: "1",
        maidens: 0,
        wickets: 0,
        runs: 12,
        economy: "12",
        name: "Sher Malla",
        nickname: "Sher Malla",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 6,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 1426791,
        overs: "3.2",
        maidens: 0,
        wickets: 0,
        runs: 26,
        economy: "7.8",
        name: "Thomas Draca",
        nickname: "Thomas Draca",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 20,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "IN",
      },
      {
        id: 11050,
        overs: "3",
        maidens: 0,
        wickets: 0,
        runs: 22,
        economy: "7.3",
        name: "D Arcy Short",
        nickname: "D Arcy Short",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 18,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 8030,
        overs: "3",
        maidens: 0,
        wickets: 0,
        runs: 27,
        economy: "9",
        name: "Gulbadin Naib",
        nickname: "Gulbadin",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 18,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 22746,
        overs: "1",
        maidens: 0,
        wickets: 5,
        runs: 8,
        economy: "8",
        name: "Tilak Bhandari",
        nickname: "Tilak Bhandari",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 6,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
    ],
  },
  event: {
    type: "four",
    batterId: 8426,
    batterName: "Harmeet Singh",
    runs: 7,
    balls: 3,
    bowlerName: "appa",
    wickets: 8,
    overs: 10,
  },
  players: {
    striker: "Binod Bhandari",
    nonStriker: "Harmeet Singh",
    strikerRuns: "",
    strikerBallsPlayed: "",
    nonStrikerRuns: "",
    nonStrikerBallsPlayed: "",
    bowler: "Thomas Draca",
  },
  displayMatchObject: {
    event: {
      type: "SIX",
      batterId: 8426,
      batterName: "Harmeet Singh",
      runs: 7,
      balls: 3,
    },
    team1: "Lumbini Lions",
    team2: "Sudur Paschim Royals",
    team1Short: "LUL",
    team2Short: "SPR",
    format: "T20",
    status: "Sudur Paschim Royals won by 7 wkts",
    players: {
      striker: "Binod Bhandari",
      nonStriker: "Harmeet Singh",
      strikerRuns: "",
      strikerBallsPlayed: "",
      nonStrikerRuns: "",
      nonStrikerBallsPlayed: "",
      bowler: "Thomas Draca",
    },
  },
};
