export const matchContextData_all_milestones = {
  match: {
    name: "Sydney Sixers Women vs Sydney Thunder Women",
    team1: "Sydney Sixers Women",
    team2: "Sydney Thunder Women",
    team1Short: "SYSW",
    team2Short: "SYTW",
    format: "T20",
    status: "Sydney Sixers Women need 134 runs in 91 balls",
    venue: "",
    isMatchComplete: false,
  },

  event: {
    type: "FOUR",

    bat1: "Sophia Dunkley",
    bat2: "Perry Test1",
    runs: 54,
    balls: 35,
    currentOver: "5.5",
    ballNbr: 35,
    commentaryTexts: [],
    bowlerName: "Taneale Peschel",
    inningsid: 2,
    wickets: 0,
    overs: 5.5,
    batteamname: "Sydney Sixers Women",
    batteamsname: "SYSW",

    partnership: {
      totalRuns: 120,
      totalBalls: 35,
      bat1: {
        name: "Sophia Dunkley",
        runs: 100,
        balls: 26,
      },
      bat2: {
        name: "Perry",
        runs: 12,
        balls: 9,
      },
      currentRunningOver: 5.5,
    },
    targetInning: {
      targetRuns: 174,
      targetWicket: 6,
      targetOvers: 20,
      battingTeamName: "Sydney Thunder Women",
      battingTeamShortName: "SYTW",
    },
  },
  players: {
    striker: "Sophia Dunkley",
    nonStriker: "Ellyse Perry",
    strikerRuns: "",
    strikerBallsPlayed: "",
    nonStrikerRuns: "",
    nonStrikerBallsPlayed: "",
    bowler: "Taneale Peschel",
  },
};

export const matchContextData_partnership = {
  event: {
    type: "PARTNERSHIP_MILESTONE",
    bat1: "Kohli",
    bat2: "Rohit",
    runs: 125,
    balls: 82,
    currentOver: "16.5",
    ballNbr: 101,
    commentaryTexts: [
      "Subrayen to Rohit, 1 run, flighted delivery outside off, driven in front of square on the off-side for a single, brings up the B0$",
    ],
    bowlerName: "Prenelan Subrayen",
    inningsid: 1,
    wickets: 1,
    overs: 16.5,
    batteamname: "India",
    batteamsname: "IND",
    batsman: [
      {
        id: 13940,
        balls: 16,
        runs: 18,
        fours: 2,
        sixes: 1,
        strkrate: "112.5",
        name: "Yashasvi Jaiswal",
        nickname: "Yashasvi Jaiswal",
        iscaptain: false,
        iskeeper: false,
        outdec: "c de Kock b Nandre Burger",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 576,
        balls: 40,
        runs: 47,
        fours: 5,
        sixes: 2,
        strkrate: "117.5",
        name: "Rohit Sharma",
        nickname: "Rohit",
        iscaptain: false,
        iskeeper: false,
        outdec: "batting",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 1413,
        balls: 45,
        runs: 46,
        fours: 4,
        sixes: 2,
        strkrate: "102.22",
        name: "Virat Kohli",
        nickname: "Kohli",
        iscaptain: false,
        iskeeper: false,
        outdec: "batting",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 11813,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Ruturaj Gaikwad",
        nickname: "Ruturaj Gaikwad",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 10945,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Washington Sundar",
        nickname: "Washington Sundar",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 8733,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "KL Rahul",
        nickname: "Rahul",
        iscaptain: true,
        iskeeper: true,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 587,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Ravindra Jadeja",
        nickname: "Ravindra Jadeja",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 24729,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Harshit Rana",
        nickname: "Harshit Rana",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 8292,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Kuldeep Yadav",
        nickname: "Kuldeep Yadav",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 13217,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Arshdeep Singh",
        nickname: "Arshdeep Singh",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 10551,
        balls: 0,
        runs: 0,
        fours: 0,
        sixes: 0,
        strkrate: "0",
        name: "Prasidh Krishna",
        nickname: "Prasidh",
        iscaptain: false,
        iskeeper: false,
        outdec: "",
        videotype: "",
        videourl: "",
        videoid: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        iscbplusfree: false,
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
    ],
    bowler: [
      {
        id: 14565,
        overs: "4",
        maidens: 0,
        wickets: 0,
        runs: 30,
        economy: "7.5",
        name: "Marco Jansen",
        nickname: "Marco Jansen",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 24,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 13630,
        overs: "4",
        maidens: 0,
        wickets: 1,
        runs: 26,
        economy: "6.5",
        name: "Nandre Burger",
        nickname: "Nandre Burger",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 24,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 9576,
        overs: "3",
        maidens: 0,
        wickets: 0,
        runs: 19,
        economy: "6.3",
        name: "Corbin Bosch",
        nickname: "Corbin Bosch",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 18,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 13100,
        overs: "3",
        maidens: 0,
        wickets: 0,
        runs: 22,
        economy: "7.3",
        name: "Ottneil Baartman",
        nickname: "Ottneil Baartman",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 18,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
      {
        id: 8530,
        overs: "2.5",
        maidens: 0,
        wickets: 0,
        runs: 21,
        economy: "7.4",
        name: "Prenelan Subrayen",
        nickname: "Subrayen",
        iscaptain: false,
        iskeeper: false,
        videotype: "",
        videourl: "",
        videoid: 0,
        dots: 0,
        balls: 17,
        rpb: 0,
        planid: 0,
        imageid: 0,
        premiumvideourl: "",
        ispremiumfree: false,
        inmatchchange: "",
        isoverseas: false,
        playingxichange: "",
      },
    ],
  },
  partnership: {
    totalRuns: 25,
    totalBalls: 19,
    bat1: { name: "Jaiswal", runs: 18, balls: 16 },
    bat2: { name: "Rohit", runs: 1, balls: 3 },
    currentRunningOver: 16.5,
  },
  targetInning: {
    targetRuns: 125,
    targetWicket: 1,
    targetOvers: 16.5,
    battingTeamName: "India",
    battingTeamShortName: "IND",
  },
};
