export const EVENT_TYPES = {
  SIX: "SIX",
  FOUR: "FOUR",
  WICKET: "WICKET",
  BATSMAN_MILESTONE: "BATSMAN_MILESTONE",
  BOWLER_MILESTONE: "BOWLER_MILESTONE",
  TEAM_MILESTONE: "TEAM_MILESTONE",
  PARTNERSHIP_MILESTONE: "PARTNERSHIP_MILESTONE",
};

export const BATSMAN_MILESTONE_RUNS = 50;
export const TEAM_MILESTONE_RUNS = 50;
export const PARTNERSHIP_MILESTONE_RUNS = 50;

export const BOWLER_MILESTONE_WICKETS = 5;
export const PARTNERSHIP_UPDATED = "PARTNERSHIP_UPDATED";

export const ALLOWED_EVENTS = Object.values(EVENT_TYPES);
